server:
  port: 8001

eureka:
  instance:
    hostname: 10.104.102.225

  server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 5000

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/