eureka:
  client:
    serviceUrl:
      defaultZone: http://10.104.102.225:8001/eureka/

server:
  port: 8003

spring:
  application:
    name: api-base
  datasource:
    url: jdbc:mysql://10.104.102.225:3306/qtccloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin@123
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true