eureka:
  client:
    serviceUrl:
      defaultZone: http://10.104.108.177:8001/eureka/
      healthcheck:
        enabled: true
    instance:
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 20

security:
  basic:
    enabled: false

server:
  port: 8003

spring:
  application:
    name: api-base
  datasource:
    url: jdbc:mysql://10.104.20.123:3306/qtccloud?useUnicode=true&characterEncoding=utf8
    username: developer
    password: developer1015
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true

ribbon:
  eureka:
    enable: true