server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:8001/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

security:
  basic:
    enabled: false

spring:
  application:
    name: api-base
  datasource:
    url: jdbc:mysql://10.104.20.123:3306/qtccloud?useUnicode=true&characterEncoding=utf8
    username: developer
    password: developer1015
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true

ribbon:
  eureka:
    enable: true

file:
  filePath: e:/file/uploaded_files/
  pre: /files
  server: http://${spring.cloud.client.ipAddress}:${server.port}

swagger:
  base-package: com.ucar.qtc.base.controller