server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.104.108.177:8001/eureka/
    healthcheck:
      enabled: true

  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: 10.104.108.177:${server.port}

security:
  basic:
    enabled: false

spring:
  application:
    name: api-base
  datasource:
    url: jdbc:mysql://10.104.20.123:3306/qtccloud?useUnicode=true&characterEncoding=utf8
    username: developer
    password: developer1015
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true

ribbon:
  eureka:
    enable: true

file:
  filePath: /file/uploaded_files/
  pre: /files
  server: http://10.104.108.177:8003