server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.104.108.177:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: 10.104.108.177:${server.port}

spring:
  application:
    name: zuul

  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
    eureka:
      enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000