server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.104.108.177:8001/eureka/
    healthcheck:
      enabled: true

  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: 10.104.108.177:${server.port}

spring:
  application:
    name: zuul

  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

  redis:
      hostName: 10.104.108.177
      port: 6379
      jedis:
        pool:
          maxActive: 1024
          maxWait: 1000
          maxIdle: 200
      timeout: 10000

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 30000
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000