eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

server:
  port: 8002

spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000