server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:8001/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

  redis:
    host: 10.104.108.177
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-wait: -1s
        max-idle: 200
    timeout: 500s

zuul:
#  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000


multipart:
   maxFileSize: 50Mb
   maxRequestSize: 50Mb