server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.103.13.217:8001/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: 10.103.13.217:${server.port}

spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 30000
  eureka:
    enabled: true