eureka:
  client:
    serviceUrl:
      defaultZone: http://qtc:123456@localhost:8001/eureka/
security:
  basic:
    enabled: false
server:
  port: 8006
logging:
  level: debug
spring:
  application:
    name: front-end-service