server:
  port: 8006

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:8001/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

security:
  basic:
    enabled: false

logging:
  level:
    root: INFO

spring:
  application:
    name: api-home

ribbon:
   ReadTimeout: 60000
   ConnectTimeout: 30000
   eureka:
     enabled: true
