eureka:
  client:
    serviceUrl:
      defaultZone: http://10.103.14.221:8001/eureka/
  instance:
    prefer-ip-address: true
security:
  basic:
    enabled: false
server:
  port: 8006
logging:
  level: debug
spring:
  application:
    name: api-home