server:
  port: 8006

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.104.108.177:8001/eureka/
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: 10.104.108.177:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: api-home
  servlet:
      multipart:
        max-file-size: 100Mb
        max-request-size: 100Mb

