eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
security:
  basic:
    enabled: false
server:
  port: 8006
spring:
  application:
    name: api-home
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qtccloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
logging:
  level: debug