server:
  port: 8006

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: localhost:${server.port}

security:
  basic:
    enabled: false

logging:
  level: debug

spring:
  application:
    name: api-home

ribbon:
   ReadTimeout: 60000
   ConnectTimeout: 30000
   eureka:
     enabled: true
