server:
  port: 8004

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.104.108.177:8001/eureka/
    registry-fetch-interval-seconds: 15
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    instance-id: 10.104.108.177:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'

cache:
  time: 5

spring:
  application:
    name: api-admin
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  redis:
    host: 10.104.108.177
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-wait: -1s
        max-idle: 200
    timeout: 500s

jdbc:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.104.20.123:3306/qtccloud?useUnicode=true&characterEncoding=utf8
    username: developer
    password: developer1015
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 100
    filters: stat,wall,slf4j

mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true

logging:
  level:
    root: INFO

ribbon:
  eureka:
    enable: true
