eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

security:
  basic:
    enabled: false

server:
  port: 8004

spring:
  application:
    name: api-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qtccloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true
logging:
  level: debug

ribbon:
  eureka:
    enable: true

file:
  filePath: e:/file/uploaded_files/
  pre: /files
  server: http://10.103.13.242:8004
