server:
  port: 8004

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}

security:
  basic:
    enabled: false

spring:
  application:
    name: api-admin
  datasource:
    url: jdbc:mysql://10.104.20.123:3306/qtccloud?useUnicode=true&characterEncoding=utf8
    username: developer
    password: developer1015
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true
logging:
  level: debug

ribbon:
  eureka:
    enable: true
